### DISCUSSION TITLE
Profile resolver: Interaction between inclusion/exclusion and mapping

### DISCUSSION THREAD

**Discussion by galtm** [usnistgov/OSCAL#1116] [Q&A]
Related to the [profile resolver spec's](https://pages.nist.gov/OSCAL/concepts/processing/profile-resolution/) Mapping Controls section, I'd like to know how the inclusion/exclusion process interacts with the mapping process. Is mapping done strictly after inclusion/exclusion?

For instance, would a control with ID `ac-1` be included and then mapped to ID ac-2, or would it be mapped to ID ac-2 first and thus excluded? Would a control with ID `xyz` be omitted, or would it be mapped to ID ac-3 and thus included?
```
    - include-controls:
       - matching:
          - pattern: "ac*" 
    - exclude-controls:
       - with-ids:
          - ac-2
      mapping:
       - controls:
          - from: ac-1
            to: ac-2
          - from: xyz
            to: ac-3
```
