### ISSUE TITLE
why are description fields mandatory?

### ISSUE THREAD

**Issue by mruge-shr** [usnistgov/OSCAL#1725]
### Question

Description fields are validated with a `min-occurs=1`  [for example](https://github.com/usnistgov/OSCAL/blob/6e9dc7a5aca3052e8a448ed94a0a104761cb1708/src/metaschema/oscal_component_metaschema.xml#L289-L304)

I feel many of the components do not *need* a description, for example, they are just referencing or including another document.  Is there a reason or logic behind this?

Component Definition Example

```yaml
  capabilities:

    - uuid: bf92dc8a-d8a9-4b85-92d6-8ce1c5e39780
      name: Overview
      description: ""
      incorporates-components:
        - component-uuid: 39c57559-3da4-4ed0-997d-c2da639fa498
          description: ""
```
