### ISSUE TITLE
Catalog control parts require NIST-specific part structure even with a different namespace

### ISSUE THREAD

**Issue by xee5ch** [usnistgov/OSCAL#2112]
### Describe the bug

As a developer of OSCAL catalog content and using OSCAL-enabled tools, I would like to be able to define a control without `part[@name="statement"]` or a corresponding `prop[@name="status]/@value` of `"withdrawn"` for parts outside of the OSCAL namespace.

This requirement is enforced by the `oscal-catalog-control-require-statement-when-not-withdrawn` constraint below, which needs to be adjusted.

https://github.com/usnistgov/OSCAL/blob/1eb7d81f8bc6b62dbdde7c3abbc2789a1c54914f/src/metaschema/oscal_catalog_metaschema.xml#L222-L230

### Who is the bug affecting

Developers of OSCAL catalogs with data that is not in the core OSCAL namespace.

### What is affected by this bug

Metaschema, Modeling

### How do we replicate this issue

1. Create a catalog like so.

```yaml
---
catalog:
  uuid: 546aecef-bad9-4cfe-9679-edd5775f9d06
  metadata:
    title: Example Catalog for Issue
    published: 2025-02-20T00:00:00Z
    last-modified: 2025-02-20T00:00:00Z
    version: alpha
  groups:
  - id: g1
    class: family
    title: Example Group
    controls:
      - id: g1-c1
        class: g1
        title: Example Control
        parts:
        - id: g1-c1-p1
          name: recommendation
          ns: https://example/ns/oscal
          prose: "Example"
```

3. Validate with the CLI.
4. Observe the following error.

```sh
oscal-cli validate '/home/me/catalog.yml'
Validating 'file:/home/me/catalog.yml' as YAML.
Validation identified the following issues:
[ERROR] [/catalog/group[1]/control[1]] catalog-control-require-statement-when-not-withdrawn: Expect constraint 'prop[@name='status']/@value=('withdrawn','Withdrawn') or part[@name='statement']' did not match the data at path '/catalog/group[1]/control[1]'
The file 'file:/home/me/catalog.yml' is invalid.
```

### Expected behavior (i.e. solution)

This catalog validates without an error.

### Other comments

I will propose a more targeted constraint change in an upcoming PR to resolve this issue.
